{"Team":"CustomerTeam","App":"OrderingApi","Version":"1.0.0.0","Environment":"Development","Timestamp":"2023-05-01T16:04:15.6057412+00:00","Level":"Error","Exception":"System.NullReferenceException: Object reference not set to an instance of an object.\n   at CesarBmx.Ordering.Application.Consumers.CancelOrderConsumer.Consume(ConsumeContext`1 context) in C:\\cesarc\\GitHub\\OrderingApi\\CesarBmx.Ordering.Application\\Consumers\\CancelOrderConsumer.cs:line 53"}
{"Team":"CustomerTeam","App":"OrderingApi","Version":"1.0.0.0","Environment":"Development","Timestamp":"2023-05-01T16:04:16.3440122+00:00","Level":"Error","Exception":"AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.\n\nMapping types:\nOrder -> OrderSubmitted\nCesarBmx.Ordering.Domain.Models.Order -> CesarBmx.Shared.Messaging.Ordering.Events.OrderSubmitted\n   at lambda_method414(Closure , Object , OrderSubmitted , ResolutionContext )\n   at CesarBmx.Ordering.Application.Consumers.SubmitOrderConsumer.Consume(ConsumeContext`1 context) in C:\\cesarc\\GitHub\\OrderingApi\\CesarBmx.Ordering.Application\\Consumers\\SubmitOrderConsumer.cs:line 63\n   at CesarBmx.Ordering.Application.Consumers.SubmitOrderConsumer.Consume(ConsumeContext`1 context) in C:\\cesarc\\GitHub\\OrderingApi\\CesarBmx.Ordering.Application\\Consumers\\SubmitOrderConsumer.cs:line 63"}
{"Team":"CustomerTeam","App":"OrderingApi","Version":"1.0.0.0","Environment":"Development","Timestamp":"2023-05-01T16:04:16.3440561+00:00","Level":"Error","Exception":"AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.\n\nMapping types:\nOrder -> OrderSubmitted\nCesarBmx.Ordering.Domain.Models.Order -> CesarBmx.Shared.Messaging.Ordering.Events.OrderSubmitted\n   at lambda_method414(Closure , Object , OrderSubmitted , ResolutionContext )\n   at CesarBmx.Ordering.Application.Consumers.SubmitOrderConsumer.Consume(ConsumeContext`1 context) in C:\\cesarc\\GitHub\\OrderingApi\\CesarBmx.Ordering.Application\\Consumers\\SubmitOrderConsumer.cs:line 63\n   at CesarBmx.Ordering.Application.Consumers.SubmitOrderConsumer.Consume(ConsumeContext`1 context) in C:\\cesarc\\GitHub\\OrderingApi\\CesarBmx.Ordering.Application\\Consumers\\SubmitOrderConsumer.cs:line 63"}
{"Team":"CustomerTeam","App":"OrderingApi","Version":"1.0.0.0","Environment":"Development","Timestamp":"2023-05-01T16:14:36.0190857+00:00","Level":"Error","Exception":"Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.\n ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_Orders'. Cannot insert duplicate key in object 'dbo.Orders'. The duplicate key value is (b30aa59e-a281-48da-8008-636ab0a59684).\nThe statement has been terminated.\n   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__203_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location ---\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location ---\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)\nClientConnectionId:f6135271-b261-4ad1-8eec-4663bb055a26\nError Number:2627,State:1,Class:14\n   --- End of inner exception stack trace ---\n   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)\n   at CesarBmx.Ordering.Application.Consumers.SubmitOrderConsumer.Consume(ConsumeContext`1 context) in C:\\cesarc\\GitHub\\OrderingApi\\CesarBmx.Ordering.Application\\Consumers\\SubmitOrderConsumer.cs:line 60"}
{"Team":"CustomerTeam","App":"OrderingApi","Version":"1.0.0.0","Environment":"Development","Timestamp":"2023-05-01T16:14:36.0190773+00:00","Level":"Error","Exception":"Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.\n ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_Orders'. Cannot insert duplicate key in object 'dbo.Orders'. The duplicate key value is (a1943f53-65b3-4b47-996f-7b9e43026d47).\nThe statement has been terminated.\n   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__203_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location ---\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location ---\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)\nClientConnectionId:e66aab3a-e969-44fe-bf8e-ce752ffd47f2\nError Number:2627,State:1,Class:14\n   --- End of inner exception stack trace ---\n   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)\n   at CesarBmx.Ordering.Application.Consumers.SubmitOrderConsumer.Consume(ConsumeContext`1 context) in C:\\cesarc\\GitHub\\OrderingApi\\CesarBmx.Ordering.Application\\Consumers\\SubmitOrderConsumer.cs:line 60"}
{"Team":"CustomerTeam","App":"OrderingApi","Version":"1.0.0.0","Environment":"Development","Timestamp":"2023-05-01T16:14:55.1915900+00:00","Level":"Error","Exception":"AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.\n\nMapping types:\nOrder -> OrderCancelled\nCesarBmx.Ordering.Domain.Models.Order -> CesarBmx.Shared.Messaging.Ordering.Events.OrderCancelled\n   at lambda_method415(Closure , Object , OrderCancelled , ResolutionContext )\n   at CesarBmx.Ordering.Application.Consumers.CancelOrderConsumer.Consume(ConsumeContext`1 context) in C:\\cesarc\\GitHub\\OrderingApi\\CesarBmx.Ordering.Application\\Consumers\\CancelOrderConsumer.cs:line 59"}
{"Team":"CustomerTeam","App":"OrderingApi","Version":"1.0.0.0","Environment":"Development","Timestamp":"2023-05-01T16:18:43.1192543+00:00","Level":"Error","Exception":"System.NullReferenceException: Object reference not set to an instance of an object.\n   at CesarBmx.Ordering.Application.Consumers.CancelOrderConsumer.Consume(ConsumeContext`1 context) in C:\\cesarc\\GitHub\\OrderingApi\\CesarBmx.Ordering.Application\\Consumers\\CancelOrderConsumer.cs:line 53"}
